// File autogenerated by generate_dadda.py
// DO NOT MODIFY

module dadda_tree(
    input  logic [8:0] i_rows_0,
    input  logic [8:0] i_rows_1,
    input  logic [8:0] i_rows_2,
    input  logic [8:0] i_rows_3,
    input  logic [8:0] i_rows_4,

    input  logic i_signs_0,
    input  logic i_signs_1,
    input  logic i_signs_2,
    input  logic i_signs_3,
    input  logic i_signs_4,

    output logic [16:0] o_sums,
    output logic [16:0] o_carries
);
    logic [1:0] layer_03_col_00;
    logic [0:0] layer_03_col_01;
    logic [2:0] layer_03_col_02;
    logic [1:0] layer_03_col_03;
    logic [3:0] layer_03_col_04;
    logic [2:0] layer_03_col_05;
    logic [4:0] layer_03_col_06;
    logic [3:0] layer_03_col_07;
    logic [4:0] layer_03_col_08;
    logic [4:0] layer_03_col_09;
    logic [4:0] layer_03_col_10;
    logic [4:0] layer_03_col_11;
    logic [3:0] layer_03_col_12;
    logic [2:0] layer_03_col_13;
    logic [2:0] layer_03_col_14;
    logic [1:0] layer_03_col_15;

    logic [1:0] layer_02_col_00;
    logic [0:0] layer_02_col_01;
    logic [2:0] layer_02_col_02;
    logic [1:0] layer_02_col_03;
    logic [3:0] layer_02_col_04;
    logic [2:0] layer_02_col_05;
    logic [3:0] layer_02_col_06;
    logic [3:0] layer_02_col_07;
    logic [3:0] layer_02_col_08;
    logic [3:0] layer_02_col_09;
    logic [3:0] layer_02_col_10;
    logic [3:0] layer_02_col_11;
    logic [3:0] layer_02_col_12;
    logic [3:0] layer_02_col_13;
    logic [2:0] layer_02_col_14;
    logic [1:0] layer_02_col_15;

    logic [1:0] layer_01_col_00;
    logic [0:0] layer_01_col_01;
    logic [2:0] layer_01_col_02;
    logic [1:0] layer_01_col_03;
    logic [2:0] layer_01_col_04;
    logic [2:0] layer_01_col_05;
    logic [2:0] layer_01_col_06;
    logic [2:0] layer_01_col_07;
    logic [2:0] layer_01_col_08;
    logic [2:0] layer_01_col_09;
    logic [2:0] layer_01_col_10;
    logic [2:0] layer_01_col_11;
    logic [2:0] layer_01_col_12;
    logic [2:0] layer_01_col_13;
    logic [2:0] layer_01_col_14;
    logic [2:0] layer_01_col_15;

    logic [1:0] layer_00_col_00;
    logic [0:0] layer_00_col_01;
    logic [1:0] layer_00_col_02;
    logic [1:0] layer_00_col_03;
    logic [1:0] layer_00_col_04;
    logic [1:0] layer_00_col_05;
    logic [1:0] layer_00_col_06;
    logic [1:0] layer_00_col_07;
    logic [1:0] layer_00_col_08;
    logic [1:0] layer_00_col_09;
    logic [1:0] layer_00_col_10;
    logic [1:0] layer_00_col_11;
    logic [1:0] layer_00_col_12;
    logic [1:0] layer_00_col_13;
    logic [1:0] layer_00_col_14;
    logic [1:0] layer_00_col_15;
    logic [0:0] layer_00_col_16;

    // ==== INPUTS ====
    assign layer_03_col_00 = {i_rows_0[0], i_signs_0};
    assign layer_03_col_01 = {i_rows_0[1]};
    assign layer_03_col_02 = {i_rows_0[2], i_rows_1[0], i_signs_1};
    assign layer_03_col_03 = {i_rows_0[3], i_rows_1[1]};
    assign layer_03_col_04 = {i_rows_0[4], i_rows_1[2], i_rows_2[0], i_signs_2};
    assign layer_03_col_05 = {i_rows_0[5], i_rows_1[3], i_rows_2[1]};
    assign layer_03_col_06 = {i_rows_0[6], i_rows_1[4], i_rows_2[2], i_rows_3[0], i_signs_3};
    assign layer_03_col_07 = {i_rows_0[7], i_rows_1[5], i_rows_2[3], i_rows_3[1]};
    assign layer_03_col_08 = {i_rows_0[8], i_rows_1[6], i_rows_2[4], i_rows_3[2], i_rows_4[0]};
    assign layer_03_col_09 = {i_signs_0, i_rows_1[7], i_rows_2[5], i_rows_3[3], i_rows_4[1]};
    assign layer_03_col_10 = {i_signs_0, i_rows_1[8], i_rows_2[6], i_rows_3[4], i_rows_4[2]};
    assign layer_03_col_11 = {~i_signs_0, ~i_signs_1, i_rows_2[7], i_rows_3[5], i_rows_4[3]};
    assign layer_03_col_12 = {1'b1, i_rows_2[8], i_rows_3[6], i_rows_4[4]};
    assign layer_03_col_13 = {~i_signs_2, i_rows_3[7], i_rows_4[5]};
    assign layer_03_col_14 = {1'b1, i_rows_3[8], i_rows_4[6]};
    assign layer_03_col_15 = {~i_signs_3, i_rows_4[7]};
    
    // ===== LAYER 2 =====

    HA HA_2_0_i (.a(layer_03_col_06[0]), .b(layer_03_col_06[1]), .s(layer_02_col_06[0]), .cout(layer_02_col_07[0]));
    HA HA_2_1_i (.a(layer_03_col_07[0]), .b(layer_03_col_07[1]), .s(layer_02_col_07[1]), .cout(layer_02_col_08[0]));
    HA HA_2_2_i (.a(layer_03_col_12[0]), .b(layer_03_col_12[1]), .s(layer_02_col_12[0]), .cout(layer_02_col_13[0]));

    FA FA_2_0_i (.a(layer_03_col_08[0]), .b(layer_03_col_08[1]), .cin(layer_03_col_08[2]), .s(layer_02_col_08[1]), .cout(layer_02_col_09[0]));
    FA FA_2_1_i (.a(layer_03_col_09[0]), .b(layer_03_col_09[1]), .cin(layer_03_col_09[2]), .s(layer_02_col_09[1]), .cout(layer_02_col_10[0]));
    FA FA_2_2_i (.a(layer_03_col_10[0]), .b(layer_03_col_10[1]), .cin(layer_03_col_10[2]), .s(layer_02_col_10[1]), .cout(layer_02_col_11[0]));
    FA FA_2_3_i (.a(layer_03_col_11[0]), .b(layer_03_col_11[1]), .cin(layer_03_col_11[2]), .s(layer_02_col_11[1]), .cout(layer_02_col_12[1]));

    assign layer_02_col_00[0] = layer_03_col_00[0];
    assign layer_02_col_00[1] = layer_03_col_00[1];
    assign layer_02_col_01[0] = layer_03_col_01[0];
    assign layer_02_col_02[0] = layer_03_col_02[0];
    assign layer_02_col_02[1] = layer_03_col_02[1];
    assign layer_02_col_02[2] = layer_03_col_02[2];
    assign layer_02_col_03[0] = layer_03_col_03[0];
    assign layer_02_col_03[1] = layer_03_col_03[1];
    assign layer_02_col_04[0] = layer_03_col_04[0];
    assign layer_02_col_04[1] = layer_03_col_04[1];
    assign layer_02_col_04[2] = layer_03_col_04[2];
    assign layer_02_col_04[3] = layer_03_col_04[3];
    assign layer_02_col_05[0] = layer_03_col_05[0];
    assign layer_02_col_05[1] = layer_03_col_05[1];
    assign layer_02_col_05[2] = layer_03_col_05[2];
    assign layer_02_col_06[1] = layer_03_col_06[2];
    assign layer_02_col_06[2] = layer_03_col_06[3];
    assign layer_02_col_06[3] = layer_03_col_06[4];
    assign layer_02_col_07[2] = layer_03_col_07[2];
    assign layer_02_col_07[3] = layer_03_col_07[3];
    assign layer_02_col_08[2] = layer_03_col_08[3];
    assign layer_02_col_08[3] = layer_03_col_08[4];
    assign layer_02_col_09[2] = layer_03_col_09[3];
    assign layer_02_col_09[3] = layer_03_col_09[4];
    assign layer_02_col_10[2] = layer_03_col_10[3];
    assign layer_02_col_10[3] = layer_03_col_10[4];
    assign layer_02_col_11[2] = layer_03_col_11[3];
    assign layer_02_col_11[3] = layer_03_col_11[4];
    assign layer_02_col_12[2] = layer_03_col_12[2];
    assign layer_02_col_12[3] = layer_03_col_12[3];
    assign layer_02_col_13[1] = layer_03_col_13[0];
    assign layer_02_col_13[2] = layer_03_col_13[1];
    assign layer_02_col_13[3] = layer_03_col_13[2];
    assign layer_02_col_14[0] = layer_03_col_14[0];
    assign layer_02_col_14[1] = layer_03_col_14[1];
    assign layer_02_col_14[2] = layer_03_col_14[2];
    assign layer_02_col_15[0] = layer_03_col_15[0];
    assign layer_02_col_15[1] = layer_03_col_15[1];


    // ===== LAYER 1 =====

    HA HA_1_0_i (.a(layer_02_col_04[0]), .b(layer_02_col_04[1]), .s(layer_01_col_04[0]), .cout(layer_01_col_05[0]));
    HA HA_1_1_i (.a(layer_02_col_05[0]), .b(layer_02_col_05[1]), .s(layer_01_col_05[1]), .cout(layer_01_col_06[0]));
    HA HA_1_2_i (.a(layer_02_col_14[0]), .b(layer_02_col_14[1]), .s(layer_01_col_14[0]), .cout(layer_01_col_15[0]));

    FA FA_1_0_i (.a(layer_02_col_06[0]), .b(layer_02_col_06[1]), .cin(layer_02_col_06[2]), .s(layer_01_col_06[1]), .cout(layer_01_col_07[0]));
    FA FA_1_1_i (.a(layer_02_col_07[0]), .b(layer_02_col_07[1]), .cin(layer_02_col_07[2]), .s(layer_01_col_07[1]), .cout(layer_01_col_08[0]));
    FA FA_1_2_i (.a(layer_02_col_08[0]), .b(layer_02_col_08[1]), .cin(layer_02_col_08[2]), .s(layer_01_col_08[1]), .cout(layer_01_col_09[0]));
    FA FA_1_3_i (.a(layer_02_col_09[0]), .b(layer_02_col_09[1]), .cin(layer_02_col_09[2]), .s(layer_01_col_09[1]), .cout(layer_01_col_10[0]));
    FA FA_1_4_i (.a(layer_02_col_10[0]), .b(layer_02_col_10[1]), .cin(layer_02_col_10[2]), .s(layer_01_col_10[1]), .cout(layer_01_col_11[0]));
    FA FA_1_5_i (.a(layer_02_col_11[0]), .b(layer_02_col_11[1]), .cin(layer_02_col_11[2]), .s(layer_01_col_11[1]), .cout(layer_01_col_12[0]));
    FA FA_1_6_i (.a(layer_02_col_12[0]), .b(layer_02_col_12[1]), .cin(layer_02_col_12[2]), .s(layer_01_col_12[1]), .cout(layer_01_col_13[0]));
    FA FA_1_7_i (.a(layer_02_col_13[0]), .b(layer_02_col_13[1]), .cin(layer_02_col_13[2]), .s(layer_01_col_13[1]), .cout(layer_01_col_14[1]));

    assign layer_01_col_00[0] = layer_02_col_00[0];
    assign layer_01_col_00[1] = layer_02_col_00[1];
    assign layer_01_col_01[0] = layer_02_col_01[0];
    assign layer_01_col_02[0] = layer_02_col_02[0];
    assign layer_01_col_02[1] = layer_02_col_02[1];
    assign layer_01_col_02[2] = layer_02_col_02[2];
    assign layer_01_col_03[0] = layer_02_col_03[0];
    assign layer_01_col_03[1] = layer_02_col_03[1];
    assign layer_01_col_04[1] = layer_02_col_04[2];
    assign layer_01_col_04[2] = layer_02_col_04[3];
    assign layer_01_col_05[2] = layer_02_col_05[2];
    assign layer_01_col_06[2] = layer_02_col_06[3];
    assign layer_01_col_07[2] = layer_02_col_07[3];
    assign layer_01_col_08[2] = layer_02_col_08[3];
    assign layer_01_col_09[2] = layer_02_col_09[3];
    assign layer_01_col_10[2] = layer_02_col_10[3];
    assign layer_01_col_11[2] = layer_02_col_11[3];
    assign layer_01_col_12[2] = layer_02_col_12[3];
    assign layer_01_col_13[2] = layer_02_col_13[3];
    assign layer_01_col_14[2] = layer_02_col_14[2];
    assign layer_01_col_15[1] = layer_02_col_15[0];
    assign layer_01_col_15[2] = layer_02_col_15[1];


    // ===== LAYER 0 =====

    HA HA_0_0_i (.a(layer_01_col_02[0]), .b(layer_01_col_02[1]), .s(layer_00_col_02[0]), .cout(layer_00_col_03[0]));
    HA HA_0_1_i (.a(layer_01_col_03[0]), .b(layer_01_col_03[1]), .s(layer_00_col_03[1]), .cout(layer_00_col_04[0]));

    FA FA_0_0_i (.a(layer_01_col_04[0]), .b(layer_01_col_04[1]), .cin(layer_01_col_04[2]), .s(layer_00_col_04[1]), .cout(layer_00_col_05[0]));
    FA FA_0_1_i (.a(layer_01_col_05[0]), .b(layer_01_col_05[1]), .cin(layer_01_col_05[2]), .s(layer_00_col_05[1]), .cout(layer_00_col_06[0]));
    FA FA_0_2_i (.a(layer_01_col_06[0]), .b(layer_01_col_06[1]), .cin(layer_01_col_06[2]), .s(layer_00_col_06[1]), .cout(layer_00_col_07[0]));
    FA FA_0_3_i (.a(layer_01_col_07[0]), .b(layer_01_col_07[1]), .cin(layer_01_col_07[2]), .s(layer_00_col_07[1]), .cout(layer_00_col_08[0]));
    FA FA_0_4_i (.a(layer_01_col_08[0]), .b(layer_01_col_08[1]), .cin(layer_01_col_08[2]), .s(layer_00_col_08[1]), .cout(layer_00_col_09[0]));
    FA FA_0_5_i (.a(layer_01_col_09[0]), .b(layer_01_col_09[1]), .cin(layer_01_col_09[2]), .s(layer_00_col_09[1]), .cout(layer_00_col_10[0]));
    FA FA_0_6_i (.a(layer_01_col_10[0]), .b(layer_01_col_10[1]), .cin(layer_01_col_10[2]), .s(layer_00_col_10[1]), .cout(layer_00_col_11[0]));
    FA FA_0_7_i (.a(layer_01_col_11[0]), .b(layer_01_col_11[1]), .cin(layer_01_col_11[2]), .s(layer_00_col_11[1]), .cout(layer_00_col_12[0]));
    FA FA_0_8_i (.a(layer_01_col_12[0]), .b(layer_01_col_12[1]), .cin(layer_01_col_12[2]), .s(layer_00_col_12[1]), .cout(layer_00_col_13[0]));
    FA FA_0_9_i (.a(layer_01_col_13[0]), .b(layer_01_col_13[1]), .cin(layer_01_col_13[2]), .s(layer_00_col_13[1]), .cout(layer_00_col_14[0]));
    FA FA_0_10_i (.a(layer_01_col_14[0]), .b(layer_01_col_14[1]), .cin(layer_01_col_14[2]), .s(layer_00_col_14[1]), .cout(layer_00_col_15[0]));
    FA FA_0_11_i (.a(layer_01_col_15[0]), .b(layer_01_col_15[1]), .cin(layer_01_col_15[2]), .s(layer_00_col_15[1]), .cout(layer_00_col_16[0]));

    assign layer_00_col_00[0] = layer_01_col_00[0];
    assign layer_00_col_00[1] = layer_01_col_00[1];
    assign layer_00_col_01[0] = layer_01_col_01[0];
    assign layer_00_col_02[1] = layer_01_col_02[2];

    // ==== OUTPUTS ====
    assign o_carries[0] = layer_00_col_00[0];
    assign o_sums[0] = layer_00_col_00[1];
    assign o_carries[1] = layer_00_col_01[0];
    assign o_sums[1] = 0;
    assign o_carries[2] = layer_00_col_02[0];
    assign o_sums[2] = layer_00_col_02[1];
    assign o_carries[3] = layer_00_col_03[0];
    assign o_sums[3] = layer_00_col_03[1];
    assign o_carries[4] = layer_00_col_04[0];
    assign o_sums[4] = layer_00_col_04[1];
    assign o_carries[5] = layer_00_col_05[0];
    assign o_sums[5] = layer_00_col_05[1];
    assign o_carries[6] = layer_00_col_06[0];
    assign o_sums[6] = layer_00_col_06[1];
    assign o_carries[7] = layer_00_col_07[0];
    assign o_sums[7] = layer_00_col_07[1];
    assign o_carries[8] = layer_00_col_08[0];
    assign o_sums[8] = layer_00_col_08[1];
    assign o_carries[9] = layer_00_col_09[0];
    assign o_sums[9] = layer_00_col_09[1];
    assign o_carries[10] = layer_00_col_10[0];
    assign o_sums[10] = layer_00_col_10[1];
    assign o_carries[11] = layer_00_col_11[0];
    assign o_sums[11] = layer_00_col_11[1];
    assign o_carries[12] = layer_00_col_12[0];
    assign o_sums[12] = layer_00_col_12[1];
    assign o_carries[13] = layer_00_col_13[0];
    assign o_sums[13] = layer_00_col_13[1];
    assign o_carries[14] = layer_00_col_14[0];
    assign o_sums[14] = layer_00_col_14[1];
    assign o_carries[15] = layer_00_col_15[0];
    assign o_sums[15] = layer_00_col_15[1];
    assign o_carries[16] = layer_00_col_16[0];
    assign o_sums[16] = 0;
endmodule : dadda_tree
